In [1]:
import numpy as np
from matplotlib import pyplot as plt

In [2]:
print(np.sqrt(2))

1.4142135623730951


In [3]:
print(np.pi)
print(np.sin(0))
print(np.cos(np.pi))

3.141592653589793
0.0
-1.0


In [12]:
import random

# dir(random)
print(random.random())
help(random.random) # [0, 1) → 0은 포함하고(0이상) 1은 포함하지 않는(1미만) 범위를 표시하는 표준 표현방식이랍니다.

0.09747899443959984
Help on built-in function random:

random() method of random.Random instance
    random() -> x in the interval [0, 1).



In [13]:
arr = np.random.rand(5)
print(arr)
print(type(arr))

[0.77925804 0.76111159 0.55052085 0.34612466 0.58854169]
<class 'numpy.ndarray'>


In [16]:
print(np.random.choice(6, 10))

[5 5 1 3 2 1 5 1 0 3]


In [17]:
print(np.random.choice(10, 6, replace=False))

[3 4 5 7 1 6]


In [40]:
print(np.random.choice(6, 10, p=[0.1, 0.2, 0.3, 0.2, 0.1, 0.1]))

[2 3 0 2 3 5 3 0 5 3]
